name: fun_fluter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  shared_preferences: ^2.3.3
  flutter_screenutil: ^5.9.3
  # 下拉刷新
  pull_to_refresh: ^2.0.0
  easy_refresh: ^3.4.0
  lottie: ^3.3.0
  # 事件总线
  event_bus: ^2.0.1
  logger: ^2.5.0
  retrofit: ^4.4.1
  dio: ^5.7.0
  json_annotation: ^4.9.0
  fluttertoast: ^8.2.10
  # 网络请求日志
  pretty_dio_logger: ^1.4.0
  # 视频播放器
  chewie: ^1.8.5
  video_player: ^2.9.2
  cached_network_image: ^3.4.1
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  retrofit_generator: ^9.1.5
  build_runner: ^2.4.13
  json_serializable: ^6.9.0


flutter:

  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/image/

